Feature Created UI for Admin login
Ideas2IT/cimpar-frontend pull request #4
Opened 2024-05-27 07:45 UTC by gm-malik

``

2024-06-14 11:30 UTC, muralidharani2i requested changes

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/Sidebar.tsx
>        pathname === "editMedication" ||
also if you are having mulitple lines within useEffect or anyother. put it in separete method and name it properly. So the other developer can read the name of the method and get idea about the functionality of the code does.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/VerticalTabView.tsx
> +      if (location.pathname === PATH_NAME.PROFILE && selectedOption !== undefined) {
if (location.pathname) is unneccsary. write like this for eg. if (location.pathname && location.pathname === PATH_NAME.PROFILE && selectedOption !== undefined).

Put inside separete method of these functionality with the proper name for the code. it gives idea about the code does by reading the method name.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/appointmentForm/AppointmentForm.tsx
> +import { format } from "date-fns";
Don't use like this. Create file called DateAdapter.ts and put all your methods you are using there and call it like wrapper. this will create decoupling.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/appointmentForm/AppointmentForm.tsx
> +          if (event.key === "Enter") {
change the condition here as well.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/appointmentForm/AppointmentForm.tsx
> +                  defaultValue={new Date()}
can you pass the default values here itself defaultValues: {} as IFormData, instead of passing it as props

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/appointmentForm/AppointmentForm.tsx
> +                    //   hourPlaceholder="HH"
can you remove this if you are not gonna use it.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/appointments/Appointments.tsx
> +interface IHandlers {
bring the interfaces to the top of the file.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/customAutocomplete/CustomAutocomplete.tsx
> +  // const handleInputClick = () => {
remove all the commented the code if its unused or not gonna use in future either.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/insuranceDetails/EditInsurance.tsx
> +          if (event.key === "Enter") {
change this condition.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/loginForm/LoginForm.tsx
> +    if (role === ROLE.ADMIN) {
try to use "switch" instead of multiple if ellse.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/medication/EditMedicationDetails.tsx
> +            {isOnMedication === "yes" && (
instead of using "yes" "no" can you use boolean as value. i hope the api payload also will accept boolean for isMedicationon kind of values.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/spinner/Spinner.tsx
> +  console.log(isLoading);
remove console.log if not necesary

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/userDetails/EditUserDetails.tsx
> +          if (event.key === "Enter") {
check the condition.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/visitHistory/EditVisitHistory.tsx
> +          if (event.key === "Enter") {
check condition

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/visitHistory/EditVisitHistory.tsx
> +          if (event.key === "Enter") {
also i think method gets repeated at multiple places try to bring it to utils as common file and reuse it.

2024-06-14 11:30 UTC, muralidharani2i commented on src/components/visitHistory/EditVisitHistory.tsx
> +                    value={new Date(field.value)}
pass these as default value in react hook form payload for default.

2024-06-17 08:43 UTC, gm-malik commented on src/components/Header.tsx
> +        ></Button>
Kindly merge this PR and I will make all these changes in new PR.

2024-06-19 06:38 UTC, muralidharani2i approved these changes

2024-06-19 06:39 UTC, merged